
#define MAIL_BASE           (0x1000)
#define STIM_FREQ_REQ       (MAIL_BASE + 0x8)
#define STIM_ELECTRODE_REQ  (MAIL_BASE + 0xc)
#define STIM_DAC_GROUP      (MAIL_BASE + 0x10)

#define STIM_BASE           (0x9000)

#define ELECTRODE_ENABLE1   (STIM_BASE + 0x158)
#define ELECTRODE_ENABLE2   (STIM_BASE + 0x15c)

#define ELECTRODE_MODE1     (STIM_BASE + 0x120)
#define ELECTRODE_MODE2     (STIM_BASE + 0x124)
#define ELECTRODE_MODE3     (STIM_BASE + 0x128)
#define ELECTRODE_MODE4     (STIM_BASE + 0x12c)

#define ELECTRODE_DAC_SEL1  (STIM_BASE + 0x160)
#define ELECTRODE_DAC_SEL2  (STIM_BASE + 0x164)
#define ELECTRODE_DAC_SEL3  (STIM_BASE + 0x168)
#define ELECTRODE_DAC_SEL4  (STIM_BASE + 0x16c)
